"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import MarkdownContent from "../MarkdownContent";

type ContentType="project"|"post"|"support"|"map"|"course"|"faq";
type Entry={id:number;type:ContentType;slug:string;title:string;summary:string;body:string;category:string;imageUrl:string;linkUrl:string;status:"draft"|"published"};
type View="dashboard"|ContentType|"editor";
const definitions:{type:ContentType;label:string;plural:string;icon:string;category:string}[]=[
 {type:"post",label:"Blog post",plural:"Blog posts",icon:"✎",category:"Making"},
 {type:"project",label:"Project",plural:"Projects",icon:"◫",category:"Apps"},
 {type:"map",label:"Data map",plural:"Data maps",icon:"⌖",category:"Data"},
 {type:"course",label:"Course",plural:"Learning",icon:"▤",category:"Learning"},
 {type:"support",label:"Support article",plural:"Support",icon:"?",category:"General"},
 {type:"faq",label:"FAQ",plural:"FAQs",icon:"＋",category:"General"},
];
const definition=(type:ContentType)=>definitions.find(item=>item.type===type)!;
const fresh=(type:ContentType="post"):Omit<Entry,"id">=>({type,slug:"",title:"",summary:"",body:"",category:definition(type).category,imageUrl:"",linkUrl:"",status:"draft"});

export default function AdminEditor(){
 const [items,setItems]=useState<Entry[]>([]),[form,setForm]=useState<Entry|Omit<Entry,"id">>(fresh()),[view,setView]=useState<View>("dashboard"),[message,setMessage]=useState(""),[tab,setTab]=useState<"write"|"preview">("write"),[dragging,setDragging]=useState(false),[saving,setSaving]=useState(false),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[menu,setMenu]=useState(false);
 const area=useRef<HTMLTextAreaElement>(null),bodyFile=useRef<HTMLInputElement>(null),featureFile=useRef<HTMLInputElement>(null);
 const load=()=>fetch("/api/content?admin=1").then(r=>r.json()).then(d=>setItems(d.entries||[]));useEffect(()=>{load()},[]);
 const published=items.filter(item=>item.status==="published").length,drafts=items.length-published;
 const currentType=view==="editor"?form.type:view==="dashboard"?null:view;
 const shown=useMemo(()=>items.filter(item=>(!currentType||item.type===currentType)&&(status==="all"||item.status===status)&&`${item.title} ${item.summary} ${item.category}`.toLowerCase().includes(query.toLowerCase())),[items,currentType,status,query]);
 function go(next:View){setView(next);setQuery("");setStatus("all");setMenu(false);setMessage("")}
 function create(type:ContentType){setForm(fresh(type));setTab("write");setView("editor");setMessage("")}
 function edit(entry:Entry){setForm({...entry,linkUrl:entry.linkUrl||""});setTab("write");setView("editor");setMessage("")}
 function insert(before:string,after="",placeholder="text"){const el=area.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd,selected=form.body.slice(start,end)||placeholder;setForm({...form,body:form.body.slice(0,start)+before+selected+after+form.body.slice(end)});requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+before.length,start+before.length+selected.length)})}
 async function upload(image:File,alt:string){setMessage("Uploading image…");const data=new FormData();data.append("file",image);data.append("alt",alt);const r=await fetch("/api/media",{method:"POST",body:data});const d=await r.json();if(!r.ok){setMessage(d.error||"Upload failed");return null}return d.url as string}
 async function pickBody(e:React.ChangeEvent<HTMLInputElement>){const image=e.target.files?.[0];if(!image)return;const alt=prompt("Describe this image for accessibility:","");if(alt===null)return;const url=await upload(image,alt);if(url){insert(`![${alt||"Image"}](${url})\n\n`,"","");setMessage("Image inserted.")}e.target.value=""}
 async function setFeature(image:File){const alt=prompt("Describe this feature image for accessibility:",form.title?`Feature image for ${form.title}`:"");if(alt===null)return;const url=await upload(image,alt);if(url){setForm({...form,imageUrl:url});setMessage("Feature image uploaded.")}}
 function addVideo(){const url=prompt("Paste the YouTube video URL:");if(!url)return;const title=prompt("Video title for accessibility:","YouTube video");if(title!==null)insert(`![youtube:${title}](${url})\n\n`,"","")}
 function addCode(){const lang=prompt("Code language (for example: javascript, python, swift):","javascript")||"text";insert(`\n\n\`\`\`${lang}\n`,`\n\`\`\`\n\n`,"// Add code here")}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("Saving…");try{const r=await fetch("/api/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?`${definition(form.type).label} saved successfully${form.status==="published"?" and published":" as a draft"}.`:d.error||"Could not save.");if(r.ok){await load();setTimeout(()=>go(form.type),500)}}catch{setMessage("Could not save. Please check your connection and try again.")}finally{setSaving(false)}}
 async function remove(id:number){if(!confirm("Delete this item?"))return;await fetch(`/api/content?id=${id}`,{method:"DELETE"});await load();go(form.type)}
 return <div className="cms-shell">
  <aside className={`cms-sidebar${menu?" open":""}`}><div className="cms-brand"><span>W</span><div><b>whimbr</b><small>CONTENT STUDIO</small></div></div><nav aria-label="Content management"><button className={view==="dashboard"?"active":""} onClick={()=>go("dashboard")}><i>⌂</i>Dashboard</button>{definitions.map(item=><button key={item.type} className={currentType===item.type&&view!=="editor"?"active":""} onClick={()=>go(item.type)}><i>{item.icon}</i>{item.plural}<em>{items.filter(entry=>entry.type===item.type).length}</em></button>)}</nav><div className="cms-sidebar-foot"><span className="cms-avatar">W</span><div><b>Whimbr Studio</b><small>Site owner</small></div></div></aside>
  <section className="cms-main"><header className="cms-topbar"><div><button className="cms-mobile-menu" onClick={()=>setMenu(!menu)}>☰</button><h1>{view==="dashboard"?"Dashboard":view==="editor"?("id" in form?`Edit ${definition(form.type).label}`:`New ${definition(form.type).label}`):definition(view).plural}</h1></div>{view!=="editor"&&<button className="cms-primary" onClick={()=>create(currentType||"post")}>+ New {currentType?definition(currentType).label:"content"}</button>}</header>
   <div className="cms-content">{view==="dashboard"?<Dashboard items={items} published={published} drafts={drafts} create={create} open={go}/>:view==="editor"?<form className="cms-editor-card" onSubmit={save}><div className="cms-card-head"><div><span>{definition(form.type).label}</span><h2>{"id" in form?form.title||"Untitled content":"Create new content"}</h2></div><div><button type="button" className="cms-secondary" onClick={()=>go(form.type)}>Cancel</button><button className="cms-primary" type="submit" disabled={saving}>{saving?"Saving…":"Save changes"}</button></div></div><div className="cms-form-body">
    <div className="field-row"><label>Content type<select value={form.type} onChange={e=>setForm({...fresh(e.target.value as ContentType),status:form.status})}>{definitions.map(item=><option value={item.type} key={item.type}>{item.label}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Entry["status"]})}><option value="draft">Draft</option><option value="published">Published</option></select></label></div>
    <label>{form.type==="faq"?"Question":"Title"}<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="field-row"><label>Slug<input value={form.slug} placeholder="created-from-title" onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label></div><label>{form.type==="faq"?"Related product or short context":"Short summary"}<textarea rows={3} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label>{form.type==="course"&&<label>Udemy course URL<input type="url" value={form.linkUrl} placeholder="https://www.udemy.com/course/…" onChange={e=>setForm({...form,linkUrl:e.target.value})}/></label>}
    <div className="content-editor-label"><b>Main content</b><div className="editor-tabs"><button type="button" className={tab==="write"?"active":""} onClick={()=>setTab("write")}>Write</button><button type="button" className={tab==="preview"?"active":""} onClick={()=>setTab("preview")}>Preview</button></div></div><div className="markdown-toolbar"><button type="button" onClick={()=>insert("## ","","Heading")}>Heading</button><button type="button" onClick={()=>insert("**","**","bold text")}><b>Bold</b></button><button type="button" onClick={()=>insert("[","](https://example.com)","link text")}>Link</button><button type="button" onClick={()=>insert("- ","","List item")}>List</button><button type="button" onClick={()=>insert("> ","","Quote")}>Quote</button><button type="button" onClick={addCode}>Code block</button><button type="button" onClick={()=>bodyFile.current?.click()}>Upload image</button><button type="button" onClick={addVideo}>YouTube</button><input ref={bodyFile} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={pickBody}/></div>{tab==="write"?<textarea ref={area} className="markdown-area" rows={20} value={form.body} placeholder="Write in Markdown…" onChange={e=>setForm({...form,body:e.target.value})}/>:<div className="editor-preview"><MarkdownContent source={form.body||"*Nothing to preview yet.*"}/></div>}
    <div className="feature-field"><div className="content-editor-label"><b>Feature image</b>{form.imageUrl&&<button type="button" className="feature-remove" onClick={()=>setForm({...form,imageUrl:""})}>Remove image</button>}</div><button type="button" className={`feature-dropzone${dragging?" dragging":""}`} onClick={()=>featureFile.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);const image=e.dataTransfer.files?.[0];if(image)setFeature(image)}}>{form.imageUrl?<><img src={form.imageUrl} alt=""/><span>Click or drop a new image to replace it</span></>:<><strong>Upload feature image</strong><span>Click to choose, or drag and drop a JPEG, PNG or WebP</span></>}</button><input ref={featureFile} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const image=e.target.files?.[0];if(image)await setFeature(image);e.target.value=""}}/><details className="feature-url"><summary>Use an image URL instead</summary><input value={form.imageUrl} placeholder="https://… or /api/media/…" onChange={e=>setForm({...form,imageUrl:e.target.value})}/></details></div><div className="cms-editor-foot"><span>{message}</span>{"id" in form&&<button type="button" className="danger" onClick={()=>remove(form.id)}>Delete permanently</button>}</div>
   </div></form>:<ContentList type={view} items={shown} query={query} setQuery={setQuery} status={status} setStatus={setStatus} edit={edit} create={create}/>}</div>
  </section>
 </div>
}

function Dashboard({items,published,drafts,create,open}:{items:Entry[];published:number;drafts:number;create:(type:ContentType)=>void;open:(view:View)=>void}){const recent=items.slice(0,5);return <><div className="cms-stats"><article><span>Total content</span><b>{items.length}</b><small>Across the whole website</small></article><article><span>Published</span><b>{published}</b><small>Visible on the website</small></article><article><span>Drafts</span><b>{drafts}</b><small>Still being prepared</small></article><article><span>Content areas</span><b>{definitions.length}</b><small>Managed independently</small></article></div><div className="cms-quick">{definitions.map(item=><button key={item.type} onClick={()=>create(item.type)}><i>{item.icon}</i><b>New {item.label}</b><small>Add to {item.plural}</small></button>)}</div><div className="cms-dashboard-grid"><section className="cms-card"><div className="cms-card-head"><h2>Recent content</h2></div>{recent.map(item=><button className="cms-recent" onClick={()=>open(item.type)} key={item.id}><span><b>{item.title}</b><small>{definition(item.type).label} · {item.category}</small></span><em className={`cms-badge ${item.status}`}>{item.status}</em></button>)}</section><section className="cms-card"><div className="cms-card-head"><h2>Content overview</h2></div>{definitions.map(item=><button className="cms-overview" onClick={()=>open(item.type)} key={item.type}><i>{item.icon}</i><span><b>{item.plural}</b><small>{items.filter(entry=>entry.type===item.type&&entry.status==="published").length} published · {items.filter(entry=>entry.type===item.type&&entry.status==="draft").length} drafts</small></span><em>→</em></button>)}</section></div></>}
function ContentList({type,items,query,setQuery,status,setStatus,edit,create}:{type:ContentType;items:Entry[];query:string;setQuery:(value:string)=>void;status:string;setStatus:(value:string)=>void;edit:(entry:Entry)=>void;create:(type:ContentType)=>void}){return <section className="cms-card"><div className="cms-list-toolbar"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${definition(type).plural.toLowerCase()}…`}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Drafts</option></select></div><div className="cms-table-head"><span>Content</span><span>Category</span><span>Status</span><span>Action</span></div>{items.map(item=><div className="cms-table-row" key={item.id}><span><b>{item.title}</b><small>/{item.slug}</small></span><span>{item.category}</span><span><em className={`cms-badge ${item.status}`}>{item.status}</em></span><span><button className="cms-secondary" onClick={()=>edit(item)}>Edit</button></span></div>)}{items.length===0&&<div className="cms-empty"><b>No {definition(type).plural.toLowerCase()} found</b><p>Create your first item or adjust the filters.</p><button className="cms-primary" onClick={()=>create(type)}>+ New {definition(type).label}</button></div>}</section>}
