import Link from "next/link";
import { Arrow, Page } from "../components";
export const metadata = { title: "About | Whimbr Studio", description: "The ideas and approach behind Whimbr Studio." };
export default function About(){ return <Page>
  <section className="about-hero shell"><div className="about-intro"><p className="eyebrow">About the studio</p><h1>A small studio for <em>useful curiosities.</em></h1><p className="lede">Whimbr is an independent maker studio exploring the space where practical tools, thoughtful design and genuine curiosity overlap.</p></div><figure className="about-studio-image"><img src="/about-studio.png" alt="A warm maker workspace with a laptop, electronics prototype, map, notebook and plant"/></figure></section>
  <section className="section shell story-grid"><div className="portrait-art" aria-hidden="true"><span>W</span></div><div className="prose"><p className="eyebrow">The approach</p><h2>Making things that earn their place.</h2><p>I’m interested in small, well-considered products: the kind that solve a real problem, explain something clearly or make a daily ritual a little better.</p><p>That work moves across software, electronics, mapping and teaching. Different materials, same approach—start with the human need, remove what gets in the way and keep refining the details.</p><blockquote>“Useful first. Clear always. A little delight where it counts.”</blockquote></div></section>
  <section className="section tint"><div className="shell values"><article><span>01</span><h3>Follow curiosity</h3><p>Good ideas often begin with a question worth staying with.</p></article><article><span>02</span><h3>Make it useful</h3><p>A thoughtful object should make something meaningfully easier.</p></article><article><span>03</span><h3>Keep it human</h3><p>Clear language, inclusive design and respect for attention matter.</p></article></div></section>
  <section className="shell callout"><div><p className="eyebrow">See what’s taking shape</p><h2>Explore the latest projects.</h2></div><Link href="/projects" className="button cream">View projects <Arrow/></Link></section>
  </Page> }
