export const pageContentDefaults={
 home:{kicker:"Building in public",heroHeading:"Helpful tools,",heroAccent:"simplifying your life.",intro:"I’m building a collection of apps, projects and resources to help make everyday life simpler, more organised and a little more intentional.",primaryButton:"Explore projects",secondaryButton:"About the studio →",findHeading:"What You’ll Find Here",latestHeading:"Latest Projects",quoteHeading:"Curious about what’s taking shape?",quoteText:"Follow the projects, experiments and lessons as they develop.",quoteButton:"Visit the blog"},
 about:{pageTitle:"About Whimbr Studio",sectionTitle:"A Small Studio for Useful Curiosities",intro:"Whimbr is an independent maker studio exploring the space where practical tools, thoughtful design and genuine curiosity overlap.",paragraphOne:"I’m interested in small, well-considered products: the kind that solve a real problem, explain something clearly or make a daily ritual a little better.",paragraphTwo:"The work moves across software, electronics, mapping and teaching. Different materials, same approach—start with the human need, remove what gets in the way and keep refining the details.",guidesHeading:"What Guides the Studio",quoteHeading:"Useful first. Clear always.",quoteText:"A little delight where it counts.",button:"Explore projects"},
 maps:{pageTitle:"Data Maps",intro:"Visual explorations that turn public data into useful, understandable stories."},
 learning:{pageTitle:"Learning",intro:"Practical courses designed to take you from a useful idea to something you can confidently build and use.",sectionHeading:"Courses",emptyText:"Courses can now be added and published from the CMS."},
 support:{pageTitle:"Support & FAQ",faqEmpty:"FAQs can now be created and published from the Content Studio.",productHeading:"Product Help",popularHeading:"Popular Topics",stuckHeading:"Still Stuck?",stuckText:"Send a question, report a bug or suggest an improvement.",contactButton:"Contact support",supportEmail:"support@whimbr.studio"},
 contact:{pageTitle:"Contact Whimbr Studio",formHeading:"Send a Message",intro:"Have a question, an idea or some thoughtful feedback? I’d be glad to hear from you.",submitButton:"Send message",formNote:"Submitting opens your default email application so you can review the message before sending.",emailHeading:"Email",generalText:"For general enquiries and project questions:",generalEmail:"hello@whimbr.studio",supportText:"For product support:",supportEmail:"support@whimbr.studio",socialHeading:"Social",socialNote:"Profile links will be added once the confirmed URLs are available.",responseHeading:"Response Time",responseText:"I usually reply within two working days."},
 projects:{pageTitle:"Projects",intro:"Apps, experiments, tools and creations. Some are small, some are ambitious, all are built with curiosity."},
 blog:{pageTitle:"Welcome to the Whimbr Blog"}
} as const;
export type PageKey=keyof typeof pageContentDefaults;
export type PageContent=Record<string,string>;
export const pageLabels:Record<PageKey,string>={home:"Home",about:"About",maps:"Maps",learning:"Learning",support:"Support",contact:"Contact",projects:"Projects",blog:"Blog"};
export const fieldLabel=(key:string)=>key.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase());
